### PR TITLE
FlipAxis fix

### PR DESCRIPTION
**Pull request by ghost**
This change seems to work for me! I've also tried it with the TrainingGenerator and it works fine. Right now only the images and keypoints are being transformed, whereas the augmenters Flipud/Fliplr also transform bounding boxes/heatmaps/etc. If that's necessary, one can easily add it using the same format as [here](https://github.com/aleju/imgaug/blob/master/imgaug/augmenters/flip.py).

### CODE REVIEW

**Comment by eduramiba** [comment]
Just in case this is useful for someone: I had to revert these changes in my local copy, since they lower my models accuracy and confidence significantly.

Not sure why, though.

**Comment by ghost** [comment]
Hmm... I briefly looked back at the changes I made and the errors people are experiencing have to be a result of the change from methods \_augment\_images and \_augment\_keypoints to \_augment\_batch\_, which is the preferred way of making custom augmenters now apparently, see [this](https://imgaug.readthedocs.io/en/latest/_modules/imgaug/augmenters/meta.html). Perhaps it's incompatible with an older version of imgaug (before 0.4.0). @eduramiba what version are you using?

It'll be an easy fix to separate _augment_batch_ back into the two methods, if that's the issue.

**Comment by eduramiba** [comment]
Hi @iuls 

I tried this with imgaug 0.4.0

**Comment by ghost** [comment]
Interesting... so are you getting a different error than [this](https://github.com/jgraving/DeepPoseKit/issues/61)?

**Comment by eduramiba** [comment]
I am not getting any error, just worse results, always reproducible.
Maybe it's only with my dataset. Does it happen with yours?

Thanks

**Comment by ghost** [comment]
I honestly don't remember since I was using this repo a while ago now, but I thought I was getting similar results. You probably already tried this, but I wonder if you use the augmenter to flip some images and plot the keypoints, do you see any discrepancies there?

**Comment by eduramiba** [comment]
Hi,

In my training script, I visualize some images before the training starts so I can check that things look right and keypoints are well placed, and they do look right with both versions. That's the strange thing....

So maybe it works the same for most cases but not some edge cases.

**Comment by ghost** [comment]
That's weird... In terms of transforming the actual keypoint locations I don't think I made any changes to the old code. This change was just supposed to provide support for both left-right and up-down flips in one class. I'll investigate some more!

**Comment by eduramiba** [comment]
Thanks!

If it helps, I am doing this:

```
augmenter.append(FlipAxis(data_generator, axis=0, p=0.5))  # flip image up-down
augmenter.append(FlipAxis(data_generator, axis=1, p=0.5))  # flip image left-right 
```

**Pull request merged**
