### PR TITLE
Fix imports for Tensorflow 2.1.0

### PR DESCRIPTION
**Pull request by eduramiba**

### CODE REVIEW

**Comment by jgraving** [comment]
Thanks. I'll take a look when I get a bit of free time. Does this break compatibility with earlier versions?

**Comment by eduramiba** [comment]
Unfortunately I am not sure whether it works with tensorflow 2.0 and 1.15 but I will test it as soon as possible. Maybe it's possible to change imports dynamically depending on the tensorflow version.

**Comment by lambdaloop** [comment]
This does seem to break compatibility with tensorflow 1.12. Downgrading to 0.3.5 (before this pull request) seems to fix this. 

It would be nice to have the imports change dynamically.

**Comment by jgraving** [comment]
Ok. Thanks for the update. I'll look into this when I get a chance. Hopefully just a matter of switching the imports to `tf.compat.v2`

**Pull request merged**
